### ISSUE TITLE
Removing dependency on Piston-Quack - thoughts

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/window#43]
event_loop could be locked to `Rc<RefCell<T: Window>>` as there are few cases where you want to give up the write access to the event iterator.

However, property methods are convenient for backward compability, so a window back-end needs only to implement the get/set/action it needs. For example, the back-ends doesn't need to know that they are implementing the `Window` trait. This makes it easier to change the abstractions in the core afterwards without needing to upgrade the back-ends.

**Comment by bvssvni** [comment]
The reason I'm looking into removing Piston-Quack is because it's an ugly duck - it has different syntax than "normal" Rust. It will probably be difficult to get projects outside Piston to use it, and likewise depending on Piston might seem less attractive because of this extra thing attached to it.

Not that I see other ways to work around the problems it solves. Rust is pretty low level in this particular area, and it might get features post 1.0 that fixes it.

**Comment by bvssvni** [comment]
Could rename `Window` to `EventWindow` and add a `Window` trait with all the features. `EventWindow` can be auto implemented by `T: Window`. event_loop can change to `Rc<RefCell<EventWindow>>`.

**Comment by mitchmindtree** [comment]
Just thought I'd mention I can empathise with your thoughts here - I think quack is a very creative and clever solution, however it can be a little bit of an ugly duckling :)

**Comment by bvssvni** [comment]
I think we can assume that a window will only be used in a single thread.

`Arc<Mutex<T>>` semantics does not with generic code. Even if single operations are locked they do not prevent data races for scopes of operations.

There is a possibility that Rust will get a conservative garbage collected smart pointer some time in the future, but we could just release new versions of the piston core libs.

This leaves us with `Rc<RefCell<T>>` and `&RefCell<T>` and since `Rc` has little overhead, then in practice it would suffice with `Rc<RefCell<T>>` for all known use cases.

**Comment by bvssvni** [comment]
Done.
