### ISSUE TITLE
Move `draw_size` to `Window`

### ISSUE THREAD

**Issue by bvssvni** [PistonDevelopers/window#55]
See https://github.com/PistonDevelopers/conrod/issues/363

In order to put the draw size in `RenderArgs`, the event loop needs to know the draw size. Move it from `AdvancedWindow` to `Window`.

**Comment by zummenix** [comment]
Can we use something like `scale_factor` of a window (or probably screen?) and calculate `draw_size` based on that?

**Comment by zummenix** [comment]
Probably we need an abstraction for pixels: `pixels = points * scale`
High level libraries like [Conrod](https://github.com/PistonDevelopers/conrod) are will work with points.

**Comment by bvssvni** [comment]
The scale could in theory be different for with and height, so this might be computed indirectly.
