### ISSUE TITLE
Remove associated type Event?

### ISSUE THREAD

**Issue by aepsil0n** [PistonDevelopers/window#61]
`Event` is an associated type of the `Window` trait. However, it looks as if all implementations (at least SDL2, GLFW and Glutin) of the trait set `type Event = Input`. As a generic consumer of the window trait you most likely need to make assumptions about the structure of the events, so you may end up using something like `W: Window<Event=Input>` anyway. Hence, I wonder if it makes sense to actually fix it the event type to `Input` already in the trait definition.

Or are there any use cases for different event types?

**Comment by bvssvni** [comment]
A window back-end might emit custom events, and generic code based on the piston core should use `E: GenericEvent`. This makes it possible to change the input structure in a future version or specialize it for some back-ends.

**Comment by aepsil0n** [comment]
Ah, I see. I have seen that abstraction before. Hm… you say that generic event handling code should use `GenericEvent`. But it does not really have any structure by itself (i.e. what kind of events there are etc.), so I fail to see how it could be used for anything, which is not completely abstract. Maybe my use case is not actually generic in that sense. Is there any code using `GenericEvent` as an example?

**Comment by bvssvni** [comment]
`GenericEvent` is used everywhere, for example ai_behavior https://github.com/PistonDevelopers/ai_behavior/blob/master/src/state.rs#L266-L274 or Conrod https://github.com/PistonDevelopers/conrod/blob/master/src/ui.rs#L92. Example  The whole point is to abstract away from the structure, because that's important for maintenance.

**Comment by aepsil0n** [comment]
Hm… I think I see the deeper issue more clearly now. I would like to discuss this in more detail, but I feel like this is going a bit off-topic. Anyway, I see now, that my proposal is not a good idea without further thought. Thus closing this for now.
