### ISSUE TITLE
This repo is easy to confuse with piston/src/window and the piston_window convenience wrapper

### ISSUE THREAD

**Issue by caspark** [PistonDevelopers/window#70]
The current description of `A library for window abstraction` is confusing to newcomers when browsing through the libs of the `pistondevelopers` org, despite the note in the README.

A quick fix is to change the description to `DEPRECATED - moved into piston repo`.

Even better would be deleting this repo (does Github allow a redirect to be put into place when a repo is deleted like BitBucket does?) now that its contents have been part of the `piston` repo for a while, but that's obviously a bigger change. It seems like the issues in this repo haven't been touched since April, so arguably there wouldn't be much lost here.

This also applies to the [`input`](https://github.com/PistonDevelopers/input) and [`event_loop`](https://github.com/PistonDevelopers/event_loop/) repos as well, however a) I didn't want to spam issues and b) the problem is more pronounced for this repo due to the existence of the (IMO confusingly named!) [`piston_window`](https://github.com/PistonDevelopers/piston_window) convenience wrapper.

**Comment by bvssvni** [comment]
I'ved updated the project descriptions. Opened https://github.com/PistonDevelopers/piston/issues/967

Closing.
